name: Run Script from Repository

on:
 workflow_dispatch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          # Execute the script from the repository root directory
          chmod +x wed3.sh
          ./wed3.sh

